### ISSUE TITLE
Swift 6 and Hummingbird Postgres

### ISSUE THREAD

**Issue by thoven87** [hummingbird-project/hummingbird-postgres#20]
I know Swift 6 isn't stable yet. 

I noticed the following behavior with the latest version of Hummingbird Postgres

The following  will produce warning and causes what looks like a memory leak:

WARNING message 
`
Sending 'self'-isolated value of type '[PostgresMigrationGroup]' with later accesses to actor-isolated context risks causing data races; this is an error in the Swift 6 language mode
`

```swift
    app.beforeServerStarts {
        try await postgresMigrations.apply(client: postgresClient, logger: logger, dryRun: false)
    }
```

Memory will grow until the server is restarted.

Disabling the Postgres migration, the application stays steady at 6mb until traffic starts following. 

Swift version
`
swift-driver version: 1.112.3 Apple Swift version 6.0 (swiftlang-6.0.0.6.8 clang-1600.0.23.1)
Target: arm64-apple-macosx15.0
`

**Comment by adam-fowler** [comment]
No we'll keep it open. I've also transferred it to hummingbird-postures repo

**Comment by thoven87** [comment]
Is this still needed since [PR](https://github.com/hummingbird-project/hummingbird-postgres/pull/23) was just merged?
