### ISSUE TITLE
Service will fail to boot

### ISSUE THREAD

**Issue by thoven87** [hummingbird-project/hummingbird-postgres#24]
I think mentioned this could happened in [comment](https://github.com/hummingbird-project/swift-jobs/pull/5#discussion_r1730402817) I have a small [repository](https://github.com/thoven87/swift-jobs-postgres) setup where the service will fail to start since `setMedata` or `getMetada` is being called before [postgres-nio](https://github.com/vapor/postgres-nio/tree/main) is ready. 

This issue is not present with the redisstack and confirmed it works fine. 

The Postgres implementation will yield 

```sh
[PostgresNIO] Trying to lease connection from `PostgresClient`, but `PostgresClient.run()` hasn't been called yet.
```
and the service will hang. 

There needs to be a warning on the Swift Jobs Postgres implementation until this issue is fixed in PostgresNIO cc @fabianfett @adam-fowler

**Comment by adam-fowler** [comment]
Can you post the full log?

**Comment by adam-fowler** [comment]
Have you run the migrations?

**Comment by adam-fowler** [comment]
I think there is an issue where the getMetadata can run before the job queue migrations have finished.

**Comment by thoven87** [comment]
Here's the full
```sh
2024-08-27T13:21:24-0400 info SwiftJobsPostgres : JobName=scheduled-jobs [Jobs] Registered Job
2024-08-27T13:21:24-0400 warning SwiftJobsPostgres : [PostgresNIO] Trying to lease connection from `PostgresClient`, but `PostgresClient.run()` hasn't been called yet.
```

It does not make any difference if the following block is there or not

```swift 
    app.beforeServerStarts {
        try await postgresMigrations.apply(client: postgresClient, logger: logger, dryRun: false)
    }
```

```swift
    app.beforeServerStarts {
        try await postgresMigrations.apply(client: postgresClient, logger: logger, dryRun: true)
    }
```

**Comment by adam-fowler** [comment]
Yeah thinking about the job scheduler it should really wait for the job queue to be up and running

**Comment by adam-fowler** [comment]
Do you have a log with log level set to debug?

**Comment by thoven87** [comment]
> Do you have a log with log level set to debug?

Debug prints the same message

**Comment by thoven87** [comment]
> Yeah but it should print a whole load more messages.

Unfortunately, it does not!

**Comment by thoven87** [comment]
I think Postgres NIO needs to provide a call back when it's or which ever magic https://github.com/swift-server/RediStack is doing should be applied to Postgres NIO. RedisStack does not have this issue.

**Comment by thoven87** [comment]
> Yeah but it should print a whole load more messages.

Unfortunately, no more logs are printed, the process just hangs there. I think Postgres NIO should provide a callback once ready for do the magic https://github.com/swift-server/RediStack is currently doing. The Redis implementation does not have this issue.

**Comment by thoven87** [comment]
> Yeah but it should print a whole load more messages.

Unfortunately, it does not! Postgress NIO needs a callback or do whichever the RedisStack is currently. The Redis implementation does not have this issue.

**Comment by adam-fowler** [comment]
Can you try this branch to see if it fixes your issue https://github.com/hummingbird-project/swift-jobs/pull/17

**Comment by thoven87** [comment]
> Can you try this branch to see if it fixes your issue [hummingbird-project/swift-jobs#17](https://github.com/hummingbird-project/swift-jobs/pull/17)

That did not solve it unfortunately.

```sh
2024-08-27T18:03:57-0400 info SwiftJobsPostgres : JobName=scheduled-jobs [Jobs] Registered Job
2024-08-27T18:03:57-0400 warning SwiftJobsPostgres : [PostgresNIO] Trying to lease connection from `PostgresClient`, but `PostgresClient.run()` hasn't been called yet.
```
<img width="1512" alt="Screenshot 2024-08-27 at 6 04 19 PM" src="https://github.com/user-attachments/assets/11f80c90-62f3-408d-9a5d-6021f6b04407">

**Comment by adam-fowler** [comment]
I found the issue. You were right about the get metadata being called to early. I was calling it in the init of the scheduler service and not in `run()`. 

Try again with the `main` branch of swift-jobs.

**Comment by adam-fowler** [comment]
I'll try and get a release out before the end of the day

**Comment by thoven87** [comment]
> I'll try and get a release out before the end of the day

Thanks Adam! I am looking forward to the next release.
